# Generated by Django 3.1.1 on 2021-05-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='labels',
            new_name='img_objects',
        ),
    ]
